# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# github does not allow relative links
#relative_permalinks: true

# Setup
title:               GeneMANIA
tagline:             Help and documentation
description:         ''
url:                 http://pages.genemania.org
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              GeneMANIA
  url:               https://genemania.org
  email:             genemania_dev@googlegroups.com

# Custom vars
version:             1.0.0

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
