# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# github does not allow relative links
#relative_permalinks: true

# Setup
title:               Lanyon
tagline:             'A Jekyll theme'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://genemania.github.io/pages/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              GeneMANIA
  url:               http://genemania.org
  email:             genemania_dev@googlegroups.com

# Custom vars
version:             1.0.0
